{% set name = "earthkit-geo" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fe8772abdcc18763034ec4e9a8bc5e81c85e05680acb4653f9ebbd13a07607cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools >=61
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - earthkit.geo

about:
  home: https://github.com/ecmwf/earthkit-geo
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Geospatial computation library.
  dev_url: https://github.com/ecmwf/earthkit-geo

extra:
  recipe-maintainers:
    - iainrussell
    - sandorkertesz
    - pmaciel
