{% set name = "earthkit-geo" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ea3755f07edc97466478b9c9f97390e887842f6fd8e749f6230b9270b51716e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner
  run:
    - python >=3.8
    - scipy

test:
  imports:
    - earthkit.geo

about:
  home: https://github.com/ecmwf/earthkit-geo
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Geospatial computation library.
  dev_url: https://github.com/ecmwf/earthkit-geo

extra:
  recipe-maintainers:
    - iainrussell
    - sandorkertesz
    - pmaciel
